services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./outputs:/app/outputs
      - ./models:/app/models
      - ./driveguard.db:/app/driveguard.db
      - ./driveguard.db_uploads:/app/driveguard.db_uploads

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
